name: Backend Smoke

on: [push, pull_request]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: Backend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Start server
        run: |
          node server.js &
          echo $! > server.pid

      - name: Wait for server
        run: |
          for i in {1..40}; do
            if curl -sSf http://localhost:3001/ >/dev/null; then
              echo "Server is up"; exit 0
            fi
            echo "Waiting for server... ($i)"
            sleep 1
          done
          echo "Server failed to start"
          exit 1

      - name: Hit test endpoint
        run: |
          RES="$(curl -sS http://localhost:3001/api/test-event)"
          echo "Response: $RES"
          echo "$RES" | grep -q '"title":"TestEvent"'

      - name: Stop server
        if: always()
        run: |
          kill $(cat server.pid) || true
