name: Auto Deploy Backend to Azure Container App

on:
  push:
    branches: [ main ]
    paths:
      - 'Backend/**'
      - '.github/workflows/deploy-containerapp.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for OIDC authentication
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TESTCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Backend to Azure Container App (no registry needed)
        run: |
          # Ensure containerapp extension and providers are registered
          az extension add --name containerapp --upgrade
          az provider register --namespace Microsoft.App
          az provider register --namespace Microsoft.OperationalInsights

          # Build and deploy directly from Backend/ source folder
          az containerapp up \
            --name test-container \
            --resource-group GroupJCS3203Fall2025 \
            --location centralus \
            --source Backend \
            --ingress external \
            --target-port 3001 \
            --environment test-container-env

          # Output the public URL for verification
          echo "Public endpoint:"
          az containerapp show -n test-container -g GroupJCS3203Fall2025 \
            --query properties.configuration.ingress.fqdn -o tsv
