name: Trigger auto deployment for test-container

on:
  push:
    branches: [ main ]
    paths:
      - 'Backend/**'
      - '.github/workflows/test-container-AutoDeployTrigger-607d3135-9d5b-4f1b-82f7-e8fad12bfc7e.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # for OIDC
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TESTCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry, then deploy to ACA
        uses: azure/container-apps-deploy-action@v2
        with:
          # Build context for Docker (your backend folder)
          appSourcePath: Backend

          # Path to Dockerfile (relative to appSourcePath or repo root)
          dockerfilePath: Backend/Dockerfile

          # Your container registry login server (ACR "Login server", e.g. myregistry.azurecr.io)
          registryUrl: <YOUR-REGISTRY-LOGIN-SERVER>

          # Credentials (already generated by the portal)
          registryUsername: ${{ secrets.TESTCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTCONTAINER_REGISTRY_PASSWORD }}

          # Where to push the image (registry/repository:tag)
          imageToBuild: <YOUR-REGISTRY-LOGIN-SERVER>/test-container:${{ github.sha }}

          # Target Container App
          containerAppName: test-container
          resourceGroup: GroupJCS3203Fall2025



