name: Deploy Backend to Azure Container Apps

on:
  push:
    branches: [ main ]
    paths: [ "Backend/**", ".github/workflows/deploy-backend.yml" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure Container Apps extension
        run: az extension add --name containerapp --upgrade

      - name: Deploy (build from source)
        env:
          RG: GroupJCS3203Fall2025
          LOC: westus2                  # matches the env your logs show ("West US 2")
          APP_NAME: test-container      # your Container App name
        run: |
          az containerapp up \
            --name $APP_NAME \
            --resource-group $RG \
            --location $LOC \
            --source . \
            --ingress external \
            --target-port 3001 \
            --environment "${APP_NAME}-env"

          echo "URL:"
          az containerapp show -n $APP_NAME -g $RG \
            --query properties.configuration.ingress.fqdn -o tsv
